# Generated by Django 5.1.1 on 2024-10-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custmer_invoice_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
