# Generated by Django 5.1.2 on 2024-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_custmer_invoice_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustmerInvoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmer_name', models.CharField(max_length=2500)),
                ('custmer_address', models.CharField(max_length=2500)),
                ('custmer_phone', models.CharField(max_length=2500)),
                ('custmer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='custmer_invoice_info',
        ),
    ]
