# Generated by Django 5.1.2 on 2024-10-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_custmerinvoiceinfo_delete_custmer_invoice_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='description',
            new_name='product',
        ),
    ]
