# Generated by Django 5.1.2 on 2024-10-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0004_rename_description_invoiceitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
    ]
